Added file-loader and Clean webpack plugin.
anandgupta193/react-enterprise-starter-kit pull request #33
Opened 2020-07-19 07:13 UTC by shubhamsWEB

2020-07-19 09:02 UTC, anandgupta193 requested changes

2020-07-19 09:02 UTC, anandgupta193 commented on README.md
> +# React-Enterprise-Dtarter-Kit :fire:
please correct typo

2020-07-19 09:02 UTC, anandgupta193 commented on src/components/App.jsx
> +  <Suspense fallback={<Loader />}>
Suspense should be in routes correct?

2020-07-19 09:02 UTC, anandgupta193 commented on webpack/webpack.common.config.js
> +        test: /\.(png|jpe?g|gif|webp)$/i,
do we need to add svg's as well here?

2020-07-19 09:02 UTC, anandgupta193 commented on src/components/home/Home.jsx
> +      <svg
Let's create a separate folder inside public as svgs and put all the svgs on that, and we will go ahead and import svgs.

2020-07-19 17:51 UTC, shubhamsWEB commented on README.md
> +# React-Enterprise-Dtarter-Kit :fire:
Done

2020-07-19 17:51 UTC, shubhamsWEB commented on src/components/App.jsx
> +  <Suspense fallback={<Loader />}>
right,fixed that

2020-07-19 17:52 UTC, shubhamsWEB commented on webpack/webpack.common.config.js
> +        test: /\.(png|jpe?g|gif|webp)$/i,
Done

2020-07-19 17:53 UTC, shubhamsWEB commented on src/components/home/Home.jsx
> +      <svg
For now i have used .png image for the same, but in future we will do that

2020-07-19 19:20 UTC, anandgupta193 requested changes

2020-07-19 19:20 UTC, anandgupta193 commented on src/components/home/Home.jsx
> +      <a href="https://github.com/anandgupta193/react-enterprise-starter-kit">
get this from constants

2020-07-19 19:20 UTC, anandgupta193 commented on src/components/home/Home.jsx
> +    <span className={homeStyle.forkongithub}>
class-names should be camel case - Please fix

2020-07-19 19:20 UTC, anandgupta193 commented on src/routes/Routes.jsx
> +        <Suspense fallback={<Loader />}>
can there be only one suspense for all the routes?

2020-07-19 19:20 UTC, anandgupta193 commented on webpack/webpack.common.config.js
> +              hmr: process.env.NODE_ENV === 'production',
hmr is not handled by webpack-dev-server?

2020-07-19 19:20 UTC, anandgupta193 commented on webpack/webpack.common.config.js
> +    chunkFilename: 'assets/scripts/[name].[contenthash].js',
this is amazing

2020-07-19 19:20 UTC, anandgupta193 commented on src/routes/Routes.jsx
> +const Notfound = lazy(() => import('../components/404/NotFound'));
As discussed, Can we have separate files for this?

2020-07-19 19:20 UTC, anandgupta193 commented on src/components/home/Home.jsx
> +    <img className={homeStyle.logo} alt="React-Enterprise-Strater-Kit" src={ReactLogo} />
Get Alt text from constants

2020-07-20 06:18 UTC, anandgupta193 commented
@shubhamsWEB - Please rebase

2020-07-20 08:46 UTC, anandgupta193 approved these changes

2020-07-20 08:46 UTC, anandgupta193 commented on src/components/home/Home.jsx
> +// eslint-disable-next-line import/no-unresolved
why this eslint rule override? cant we fix this?

2020-07-20 08:46 UTC, anandgupta193 commented on src/routes/Routes.jsx
> +      <Suspense fallback={<Loader />}>
looks amazing

2020-07-20 08:46 UTC, anandgupta193 commented on src/routes/Routes.jsx
> +import { Notfound, App } from './Routes.lazy';
Can we change it to NotFound 'F capital'?

2020-07-20 08:55 UTC, akhileshbhatia requested changes

2020-07-20 08:55 UTC, akhileshbhatia commented on src/constants/HomeConstants.js
> +export const IMG_ALT = 'React-Enterprise-Strater-Kit';
```suggestion
export const IMG_ALT = 'React-Enterprise-Starter-Kit';
```

2020-07-20 08:55 UTC, akhileshbhatia commented on .stylelintrc
> +}
Add a new line

2020-07-20 08:55 UTC, akhileshbhatia commented on .stylelintignore
> +src/**/*.js
Add a new line

2020-07-20 11:31 UTC, anandgupta193 commented on .stylelintignore
> +src/**/*.js
done

2020-07-20 11:31 UTC, anandgupta193 commented on .stylelintrc
> +}
done

2020-07-20 11:31 UTC, anandgupta193 commented on src/constants/HomeConstants.js
> +export const IMG_ALT = 'React-Enterprise-Strater-Kit';
done

2020-07-20 11:57 UTC, akhileshbhatia approved these changes
LGTM

2020-07-20 18:05 UTC, anandgupta193 approved these changes

2020-07-20 18:16 UTC, merged